# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: eddded69415221e357236eb7a3624d9c66e632be946df4202a05433c2a789d339513e7231991f608f7f10392f90ca370151ddc3e7095bc9fff7cb88607c93f50

test:
  secret_key_base: 34ea06e99421008d4b4eedf5825cc921e31d1a62dfbac4aa419dab94723786c57fb816e5dc71ebf1b78e3e4ef8890f24bb59b11d33081466aa1c409cd2861846

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
